# Default values for myeventsapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: quay.io/ipedrazas/events-web
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 80

api:
  repository: quay.io/ipedrazas/events-api
  pullPolicy: Always
  service:
    name: http5000
    type: ClusterIP
    externalPort: 5000
    internalPort: 5000
db:
  user: postgres
  name: events
  migration: false
  job:
    repository: quay.io/ipedrazas/events-migration


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

