debug: true
pipeline:
  docker-web:
    environment:
          - DOCKER_API_VERSION=1.24
    image: plugins/docker:1.12
    repo: quay.io/ipedrazas/events-web
    tags: 
      - latest
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    registry: quay.io
    email: "info@info.com"
    debug: true
    dockerfile: ./client/Dockerfile
    secrets: [ docker_username, docker_password ]

  docker-api:
    environment:
          - DOCKER_API_VERSION=1.24
    image: plugins/docker:1.12
    repo: quay.io/ipedrazas/events-api
    tags: 
      - latest
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    registry: quay.io
    email: "info@info.com"
    debug: true
    dockerfile: ./events/Dockerfile
    secrets: [ docker_username, docker_password ]
  
  slack_success:
    image: plugins/slack
    channel: deploys
    username: kubot
    template: >
      {{ build.author }} finished building {{ repo.owner }}/{{ repo.name }} ({{ build.branch }})
    when:
      status: success
    secrets: [ slack_webhook]