debug: true
pipeline:
  docker:
    environment:
          - DOCKER_API_VERSION=1.24
    image: plugins/docker:1.12
    repo: quay.io/ipedrazas/events-web
    tags: 
      - latest
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    registry: quay.io
    email: "info@info.com"
    debug: true
    dockerfile: ./client/Dockerfile
    secrets: [ docker_username, docker_password ]